configMaps:
  config.json:
    data:
      config.json: |-
        {
          "greenfield_config": {
            "key_type": "local_private_key",
            "aws_region": "",
            "aws_secret_name": "",
            "aws_bls_secret_name": "",
            "rpc_addrs": [
              "gnfd-testnet-fullnode-tendermint-us.bnbchain.org:443"
            ],
            "private_key": "",
            "bls_private_key": "",
            "chain_id": 5600,
            "start_height": 1,
            "monitor_channel_list": [1,2,3,4,5,6],
            "gas_limit": 1000,
            "fee_amount": 5000000000000,
            "chain_id_string": "greenfield_5600-1"
          },
          "bsc_config": {
            "key_type": "local_private_key",
            "aws_region": "",
            "aws_secret_name": "",
            "rpc_addrs": [
              "https://data-seed-prebsc-1-s1.bnbchain.org:8545"
            ],
            "private_key": "xxxxx",
            "gas_limit": 20000000,
            "gas_price": 20000000000,
            "number_of_blocks_for_finality": 2,
            "start_height": 30995020,
            "chain_id": 97
          },
          "relay_config": {
            "bsc_to_greenfield_inturn_relayer_timeout": 40,
            "greenfield_to_bsc_inturn_relayer_timeout": 30,
            "greenfield_sequence_update_latency": 8,
            "bsc_sequence_update_latency": 12,
            "greenfield_event_type_cross_chain": "cosmos.crosschain.v1.EventCrossChain",
            "bsc_cross_chain_package_event_name": "CrossChainPackage",
            "cross_chain_package_event_hex": "0x64998dc5a229e7324e622192f111c691edccc3534bbea4b2bd90fbaec936845a",
            "cross_chain_contract_addr": "0x57b8A375193b2e9c6481f167BaECF1feEf9F7d4B",
            "greenfield_light_client_contract_addr": "0x4916f5c0688d058659aFce361E2A8F3F5b75CAd5"
          },
          "vote_pool_config": {
            "broadcast_interval_in_millisecond": 1000,
            "votes_batch_max_size_per_interval": 100,
            "query_interval_in_millisecond": 1000
          },
          "log_config": {
            "level": "DEBUG",
            "filename": "",
            "max_file_size_in_mb": 0,
            "max_backups_of_log_files": 0,
            "max_age_to_retain_log_files_in_days": 0,
            "use_console_logger": true,
            "use_file_logger": false,
            "compress": false
          },
          "admin_config": {
            "port": 8080
          },
          "db_config": {
            "dialect": "mysql",
            "key_type": "local_private_key",
            "aws_region": "",
            "aws_secret_name": "",
            "password": "xxxxx",
            "username": "xxxxx",
            "url": "tcp(xxxxx:3306)/testnet_cedar_greenfield_relayer?charset=utf8&parseTime=True&loc=Local",
            "max_idle_conns": 20,
            "max_open_conns": 130
          },
          "alert_config": {
            "identity": "your_service_name",
            "telegram_bot_id": "your_bot_id",
            "telegram_chat_id": "your_chat_id"
          }
        }
configMapsMountPath: /opt/app/config/
containers:
  env:
    - name: CONFIG_TYPE
      value: local
    - name: AWS_REGION
      value: ""
    - name: AWS_SECRET_KEY
      value: ""
    - name: CONFIG_FILE_PATH
      value: /opt/app/config/config.json
  logsMountPath: /relay/logs/

resources:
  limits:
    cpu: "4"
    memory: 4000Mi
  requests:
    cpu: 200m
    memory: 256Mi
service:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP